import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("cars").del();

  // Inserts seed entries
  await knex("cars").insert([
    {
      id: "6e2bc663-5197-441a-957b-bc75e4a2da7c",
      plate: "DBH-3491",
      manufacture: "Ford",
      model: "F150",
      image: "./images/car01.min.jpg",
      rentPerDay: 200000,
      capacity: 2,
      description:
        " Brake assist. Leather-wrapped shift knob. Glove box lamp. Air conditioning w/in-cabin microfilter.",
      transmission: "Automatic",
      available: true,
      type: "Sedan",
      year: 2022,
      image_public_id: "Ford_DBH-3491",
    },
    {
      id: "9ff03bbc-b18c-4ba7-8f3a-4c4b5c2f6c77",
      plate: "WXB-3984",
      manufacture: "BMW",
      model: "X5",
      image: "./images/car02.min.jpg",
      rentPerDay: 800000,
      capacity: 6,
      description:
        " Rear passenger map pockets. Electrochromic rearview mirror. Dual chrome exhaust tips. Locking glove box.",
      transmission: "Automatic",
      available: false,
      type: "Convertible",
      year: 2019,
      image_public_id: "BMW_WXB-3984",
    },
    {
      id: "bf6b5c43-1377-4ae0-8908-310c64266f81",
      plate: "OSL-4224",
      manufacture: "Lincoln",
      model: "MKZ",
      image: "./images/car03.min.jpg",
      rentPerDay: 900000,
      capacity: 6,
      description:
        " Driver & front passenger map pockets. Direct-type tire pressure monitor system. Cargo area lamp. Glove box lamp.",
      transmission: "Automanual",
      available: true,
      type: "Sedan",
      year: 2021,
      image_public_id: "Lincoln_OSL-4224",
    },
    {
      id: "5b67f1d7-92d4-41c7-8577-4435740aadf1",
      plate: "VPT-9753",
      manufacture: "BMW",
      model: "M5",
      image: "./images/car04.min.jpg",
      rentPerDay: 900000,
      capacity: 6,
      description: ' 6.1L SRT V8 "Hemi" engine.',
      transmission: "Manual",
      available: true,
      type: "Hatchback",
      year: 2018,
      image_public_id: "BMW_VPT-9753",
    },
    {
      id: "23574b8f-3e89-4685-a348-67c1f7e5b3c4",
      plate: "BHD-3923",
      manufacture: "Lincoln",
      model: "Navigator",
      image: "./images/car05.min.jpg",
      rentPerDay: 200000,
      capacity: 2,
      description:
        " Body color sill extension. Torsion beam rear suspension w/stabilizer bar. Front & rear passenger folding assist grips.",
      transmission: "Automatic",
      available: false,
      type: "Minivan",
      year: 2020,
      image_public_id: "Lincoln_BHD-3923",
    },
    {
      id: "3eead6db-c536-406b-9bc5-85d4c6e38a76",
      plate: "JPM-5482",
      manufacture: "Ford",
      model: "Fiesta",
      image: "./images/car06.min.jpg",
      rentPerDay: 900000,
      capacity: 4,
      description:
        " Tilt steering column. Carpeted cargo area. Tip start system. Leather-wrapped shift knob.",
      transmission: "Automanual",
      available: true,
      type: "Hatchback",
      year: 2016,
      image_public_id: "Ford_JPM-5482",
    },
    {
      id: "752685ce-dd39-40e5-9af5-93fdd36dea7e",
      plate: "BTW-1960",
      manufacture: "Honda",
      model: "Accord",
      image: "./images/car07.min.jpg",
      rentPerDay: 900000,
      capacity: 4,
      description:
        " Silver finish interior door handles. 160-amp alternator. Tire pressure monitoring system (TPMS). Cloth covered headliner.",
      transmission: "Automatic",
      available: false,
      type: "Sedan",
      year: 2020,
      image_public_id: "Honda_BTW-1960",
    },
    {
      id: "e0a96736-a2d5-40ca-87de-64b59cac85d8",
      plate: "FZQ-1989",
      manufacture: "BMW",
      model: "X3",
      image: "./images/car12.min.jpg",
      rentPerDay: 800000,
      capacity: 4,
      description: " Multi-reflector halogen headlamps. Speed control.",
      transmission: "Automanual",
      available: true,
      type: "Passenger Van",
      year: 2018,
      image_public_id: "BMW_FZQ-1989",
    },
    {
      id: "e39f2965-57da-4d8f-afdb-74f6c54e69f0",
      plate: "GAG-1943",
      manufacture: "Chevy",
      model: "Malibu",
      image: "./images/car13.min.jpg",
      rentPerDay: 900000,
      capacity: 6,
      description:
        " Leather-wrapped shift knob. Dual front illuminated visor vanity mirrors. Battery saver. Driver & front passenger map pockets.",
      transmission: "CVT",
      available: true,
      type: "SUV",
      year: 2017,
      image_public_id: "Chevy_GAG-1943",
    },
  ]);
}
